apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-container
        # Replace with the correct image name
        image: nikitapatare22/flask-app:latest
        imagePullPolicy: Always  # Ensures the latest image is pulled
        ports:
        - containerPort: 5000
